use std::str::FromStr;
use indexmap::IndexMap;
use crate::{ast::*, parse::SourceSpan};

grammar;

extern {
    type Error = crate::parse::CustomError;
}

match {
    // Skip whitespace and comments
    r"\s*" => { },
    r"//[^\n\r]*[\n\r]*" => { }, // `// comment`
    r"/\*([^\*]*\*+[^\*/])*([^\*]*\*+|[^\*])*\*/" => { }, // `/* comment */`
    _
}

Sep<T, S>: Vec<T> = {
    <mut v:(<T> S)*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};
SepNonEmpty<T, S>: Vec<T> = {
    <mut v:(<T> S)*> <e:T> =>{
        v.push(e);
        v
    }
};

#[inline]
Target: Target<Box<AExpr>> = {
    Variable => Target::Variable(<>),
    <arr:Array> "[" <idx:AExpr> "]" => Target::Array(arr, Box::new(idx)),
}
#[inline]
Variable: Variable = Var => Variable(<>);
#[inline]
Array: Array = Var => Array(<>);
#[inline]
TupleSpaceName: TupleSpaceName = Var => TupleSpaceName(<>);
#[inline]
ChannelName: ChannelName = Var => ChannelName(<>);

Function<X>: Function = {
    "division" "(" <X> "," <X> ")"  => Function::Division(<>),
    "min" "(" <X> "," <X> ")"       => Function::Min(<>),
    "max" "(" <X> "," <X> ")"       => Function::Max(<>),
    "fac" "(" <X> ")"               => Function::Fac(<>),
    "fib" "(" <X> ")"               => Function::Fib(<>),
    "exp" "(" <X> "," <X> ")"       => Function::Exp(<>),
};


pub BExpr: BExpr = {
    #[precedence(level="0")]
    <l:AExpr_> <op:RelOp> <r:AExpr_> => BExpr::Rel(l, op, r),
    "true" => BExpr::Bool(true),
    "false" => BExpr::Bool(false),
    "!" <BExpr> => BExpr::Not(Box::new(<>)),
    "(" <BExpr_> ")",

    #[precedence(level="1")] #[assoc(side="left")]
    <l:BExpr> "&" <r:BExpr> => BExpr::logic(l, LogicOp::Land, r),

    #[precedence(level="2")] #[assoc(side="left")]
    <l:BExpr> "|" <r:BExpr> => BExpr::logic(l, LogicOp::Lor, r),
};
BExpr_: BExpr = BExpr;

pub MokaBExpr: BExpr = {
    #[precedence(level="0")]
    <l:AExpr_> <op:RelOp> <r:AExpr_> => BExpr::Rel(l, op, r),
    "true" => BExpr::Bool(true),
    "false" => BExpr::Bool(false),
    "!" <MokaBExpr> => BExpr::Not(Box::new(<>)),
    "(" <MokaBExpr_> ")",
    <OperationP> => BExpr::OP(<>),

    #[precedence(level="1")] #[assoc(side="left")]
    <l:MokaBExpr> "&" <r:MokaBExpr> => BExpr::logic(l, LogicOp::Land, r),

    #[precedence(level="2")] #[assoc(side="left")]
    <l:MokaBExpr> "|" <r:MokaBExpr> => BExpr::logic(l, LogicOp::Lor, r),
};
MokaBExpr_: BExpr = BExpr;

RelOp: RelOp = {
    "<"  => RelOp::Lt,
    ">"  => RelOp::Gt,
    "<=" => RelOp::Le,
    ">=" => RelOp::Ge,
    "="  => RelOp::Eq,
    "!=" => RelOp::Ne,
};

Var: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

Int: Int = <from:@L> <int:r"[0-9]+"> <to:@R> =>? Int::from_str(int).map_err(|_| lalrpop_util::ParseError::User {
    error: crate::parse::CustomError::IntegerTooLarge { from, to },
});

// Predicates

pub AGCLCommands: Commands<PredicateChain, PredicateBlock> = SepNonEmpty<AGCLCommand, ";"> => Commands(<>);
AGCLCommand: Command<PredicateChain, PredicateBlock> = {
    <pre:PredicateChain> <l:@L> <kind:AGCLCommandKind> <r:@R> <post:PredicateChain> =>
        Command {
            pre,
            kind,
            post,
            span: (l, r - l).into(),
        }
};
AGCLCommandKind: CommandKind<PredicateChain, PredicateBlock> = {
    <Target> ":=" <AExpr>                       => CommandKind::Assignment(<>),
    "skip"                                      => CommandKind::Skip,
    "if" <AGCLGuards> "fi"                          => CommandKind::If(<>),
    "do" <PredicateInv> <AGCLGuards> "od" => CommandKind::Loop(<>),
};
AGCLGuards: Vec<Guard<PredicateChain, PredicateBlock>> = SepNonEmpty<AGCLGuard, "[]">;
AGCLGuard: Guard<PredicateChain, PredicateBlock> = {
    <l:@L> <guard:BExpr> <r:@R> "->" <cmds:AGCLCommands> => Guard { guard, cmds, guard_span: (l, r - l).into() },
};

LTLCommands: Commands<(), ()> = SepNonEmpty<LTLCommand, ";"> => Commands(<>);
LTLCommand: Command<(), ()> = {
    <l:@L> <kind:LTLCommandKind> <r:@R> =>
        Command {
            pre: (),
            kind,
            post: (),
            span: (l, r - l).into(),
        }
};
LTLCommandKind: CommandKind<(), ()> = {
    <Target> ":=" <AExpr>                       => CommandKind::Assignment(<>),
    "skip"                                      => CommandKind::Skip,
    "placeholder"                               => CommandKind::Placeholder,
    "if" <LTLCommunicationGuards> "fi"          => CommandKind::IfCG(<>),
    "do" <LTLGuards> "od"                       => CommandKind::Loop((), <>),
    "loop" <LTLCommunicationGuards> "pool"      => CommandKind::LoopCG((), <>),
    <Operation>                                 => CommandKind::O(<>),
    <ChannelName> "!" <AExpr>                        => CommandKind::Send(<>),
    <ChannelName> "?" <Target>                       => CommandKind::Receive(<>),
    <ChannelName> "!!" <Int> <AExpr>                 => CommandKind::Broadcast(<>),
    <ChannelName> "??" <Int> <Array> <Target>        => CommandKind::Gather(<>),
};
LTLGuards: Vec<Guard<(), ()>> = SepNonEmpty<LTLGuard, "[]">;
LTLGuard: Guard<(), ()> = {
    <l:@L> <guard:MokaBExpr> <r:@R> "->" <cmds:LTLCommands> => Guard { guard, cmds, guard_span: (l, r - l).into() },
};

LTLCommunicationGuards: Vec<CommunicationGuard<(), ()>> = SepNonEmpty<LTLCommunicationGuard, "[]">;
LTLCommunicationGuard: CommunicationGuard<(), ()> = {
    <l:@L> <guard:CG> <r:@R> "->" <cmds:LTLCommands> => CommunicationGuard { guard, cmds, guard_span: (l, r - l).into() },
};

CG: CG = {
    <MokaBExpr> => CG::BoolExpression(<>),
    <ChannelName> "!" <AExpr> => CG::Send(<>),
    <ChannelName> "?" <Target> => CG::Receive(<>),
}

Operation: Operation = {
    <TupleSpaceName> ".put" <TuplePut> => Operation::Put(<>),
    <TupleSpaceName> ".get" <TupleGet> => Operation::Get(<>),
    <TupleSpaceName> ".query" <TupleGet> => Operation::Query(<>),
};

OperationP: Operation = {
    <TupleSpaceName> ".putP" <TuplePut> => Operation::Put(<>),
    <TupleSpaceName> ".getP" <TupleGet> => Operation::Get(<>),
    <TupleSpaceName> ".queryP" <TupleGet> => Operation::Query(<>),
};

PredicateChain: PredicateChain = {
    <predicates:PredicateBlock*> => PredicateChain { <> }
};

PredicateBlock: PredicateBlock = {
    <l:@L> "{" <predicate:Predicate> "}" <r:@R> => PredicateBlock {
        predicate,
        span: (l, r - l).into(),
    }
};

PredicateInv: PredicateBlock = {
    <l:@L> "[" <predicate:Predicate> "]" <r:@R> => PredicateBlock {
        predicate,
        span: (l, r - l).into(),
    }
};

pub Predicate: Predicate = {
    #[precedence(level="0")]
    <l:AExpr_> <op:RelOp> <r:AExpr_> => Predicate::Rel(l, op, r),
    "true" => Predicate::Bool(true),
    "false" => Predicate::Bool(false),
    "!" <Predicate> => Predicate::Not(Box::new(<>)),
    "(" <Predicate_> ")",

    #[precedence(level="1")] #[assoc(side="left")]
    <l:Predicate> "&" <r:Predicate> => Predicate::logic(l, LogicOp::Land, r),

    #[precedence(level="2")] #[assoc(side="left")]
    <l:Predicate> "|" <r:Predicate> => Predicate::logic(l, LogicOp::Lor, r),

    #[precedence(level="3")] #[assoc(side="right")]
    <l:Predicate> "==>" <r:Predicate> => Predicate::logic(l, LogicOp::Implies, r),

    #[precedence(level="4")]
    <q:Quantifier> <v:Var> "::" <p:Predicate> => Predicate::Quantified(q, Target::Variable(Variable(v)), Box::new(p)),
};
Predicate_: Predicate = Predicate;

Quantifier: Quantifier = {
    "exists" => Quantifier::Exists,
    "forall" => Quantifier::Forall,
};

AExpr_ = AExpr;
pub AExpr: AExpr = {
    #[precedence(level="1")]
    Int => AExpr::Number(<>),
    Target => AExpr::Reference(<>),
    // TODO: see issue #58
    // "X" => AExpr::Reference(Target::Variable(Variable("X".to_string()))),
    // "G" => AExpr::Reference(Target::Variable(Variable("G".to_string()))),
    // "F" => AExpr::Reference(Target::Variable(Variable("F".to_string()))),
    Function<AExprBox> => AExpr::Function(<>),
    "-" <AExpr> => AExpr::Minus(Box::new(<>)),
    "old" "(" <Target> ")" => AExpr::Old(<>),
    "(" <AExpr_> ")",

    #[precedence(level="3")] #[assoc(side="left")]
    <l:AExpr> "*" <r:AExpr> => AExpr::binary(l, AOp::Times, r),
    <l:AExpr> "/" <r:AExpr> => AExpr::binary(l, AOp::Divide, r),

    #[precedence(level="4")] #[assoc(side="left")]
    <l:AExpr> "+" <r:AExpr> => AExpr::binary(l, AOp::Plus, r),
    <l:AExpr> "-" <r:AExpr> => AExpr::binary(l, AOp::Minus, r),
};
AExprBox: Box<AExpr> = AExpr => Box::new(<>);

// Formats

pub LTLProgram: LTLProgram = {
    <assignments:LTLInitialAssign>
    <commands:LTLCommands>
    <properties:LTLProperty*> =>? {
        crate::validate::validate_ltl_program(
            assignments,
            vec![commands],
            properties,
        )
    },

    <assignments:LTLInitialAssign>
    "par"
    <commands:SepNonEmpty<LTLCommands, "[]">>
    "rap"
    <properties:LTLProperty*> =>? {
        crate::validate::validate_ltl_program(
            assignments,
            commands,
            properties,
        )
    },
};

LTLInitialAssign: (Initial, Vec<ChannelName>) = {
    <from:@L> <lines:(">" <SepNonEmpty<LTLAssignment, ",">>)*> <to:@R> =>? {
        let mut variables = IndexMap::new();
        let mut arrays = IndexMap::new();
        let mut tuple_spaces = IndexMap::new();
        let mut async_channels = IndexMap::new(); 
        let mut sync_channels = Vec::new();
        for line in lines {
            for assignment in line {
                match assignment {
                    AssignmentKind::Int(name, val) => { variables.insert(name, val); },
                    AssignmentKind::Array(name, vals) => { arrays.insert(name, vals); },
                    AssignmentKind::TupleSpace(name, ts) => {
                        tuple_spaces.insert(name, TupleSpace {
                            space_type: ts.space_type,
                            size: ts.size,
                            space: ts.space,
                        });
                    },
                    AssignmentKind::AsyncChannel(name, ch) => {
                        async_channels.insert(name, Channel {
                            size: ch.size,
                            channel: ch.channel,
                        });
                    },
                    AssignmentKind::SyncChannel(name) => {
                        sync_channels.push(name);
                    },
                }
            }
        }
        for ac in async_channels.keys() {
            if sync_channels.contains(ac){
                return Err(lalrpop_util::ParseError::User {
                    error: crate::parse::CustomError::DuplicateChannelName {
                        name: ac.0.clone(),
                        from, 
                        to: to + ac.0.len(),
                    },
                });
            }
        }
        Ok((Initial {
            variables,
            arrays,
            tuple_spaces,
            channels: async_channels,
        }, sync_channels))
    }
};

LTLAssignment: AssignmentKind = {
    <var:Var> "=" <val:Int> => AssignmentKind::Int(Variable(var), val),
    <var:Var> "=" "-" <val:Int> => AssignmentKind::Int(Variable(var), -val),
    <var:Var> "=" <vals:ArrayInit> => AssignmentKind::Array(Array(var), vals),
    <var:Var> "=" <ts:TupleSpace> => AssignmentKind::TupleSpace(TupleSpaceName(var), TupleSpace {
        space_type: ts.0,
        size: ts.1,
        space: ts.2,
    }),
    <var:Var> "=" <ch:Channel> => AssignmentKind::AsyncChannel(ChannelName(var), Channel {
        size: ch.0,
        channel: ch.1,
    }),
    <from:@L> <var:Var> "=" "(" <size:Int> ")" <to:@R> =>? {  
        if size == 0 {  
            Ok(AssignmentKind::SyncChannel(ChannelName(var)))  
        } else {  
            Err(lalrpop_util::ParseError::User {
                error: crate::parse::CustomError::InvalidBufferSize {
                    from,
                    to,
                },
            })
        }  
    },
};

ArrayInit: Vec<i32> = {
    "[" <vals:SepNonEmpty<Value, ",">> "]" => vals,
}

TupleSpaceType: TupleSpaceType = {
    "R" => TupleSpaceType::Random,
    "Q" => TupleSpaceType::Queue,
    "S" => TupleSpaceType::Stack,
    "F" => TupleSpaceType::FIFO,
    "L" => TupleSpaceType::LIFO,
};

BufferSize: BufferSize = {
    <from:@L> <n:Int> <to:@R> =>? {
        if n == 0 {
            Err(lalrpop_util::ParseError::User {
                error: crate::parse::CustomError::InvalidBufferSize {
                    from,
                    to,
                },
            })
        } else {
            Ok(BufferSize::Finite(n))
        }
    },
    "INF" => BufferSize::Infinite,
};

TupleSpaceValues: Vec<Vec<Int>> = {
    "{" "}" => vec![],
    "{" <tuples:SepNonEmpty<Tuple, ",">> "}" => tuples,
};

ChannelValues: Vec<Int> = {
    "(" ")" => vec![],
    "(" <values:SepNonEmpty<Value, ",">> ")" => values,
};

Tuple: Vec<Int> = {
    "(" <values:SepNonEmpty<Value, ",">> ")" => values,
};

TuplePut: Vec<AExpr> = {
    "(" <values:SepNonEmpty<AExpr, ",">> ")" => values,
};

TupleGet: Vec<Field> = {
    "(" <values:SepNonEmpty<Field, ",">> ")" => values,
};

Field: Field = {
    <expr:AExpr> => Field::Expression(expr),
    "_" => Field::Any,
    "?" <Target> => Field::Target(<>),
}

Value: Int = {
    <value:Int> => value,
    "-" <value:Int> => -value,
}

TupleSpace: (TupleSpaceType, BufferSize, Vec<Vec<Int>>) = {
    <from:@L> "(" <space_type:TupleSpaceType> "," <size:BufferSize> "," <space:TupleSpaceValues> ")" <to:@R> =>? {
        match size {
            BufferSize::Finite(n) => {
                if space.len() as i32 > n {
                    Err(lalrpop_util::ParseError::User {
                        error: crate::parse::CustomError::BufferOverflow {
                            size: n,
                            actual: space.len() as i32,
                            from,
                            to,
                        },
                    })
                } else {
                    Ok((space_type, size, space))
                }
            }
            BufferSize::Infinite => {
                Ok((space_type, size, space))
            }
        }
    }
};

Channel: (BufferSize, Vec<Int>) = {
    <from:@L> "(" <size:BufferSize> "," <channel:ChannelValues> ")" <to:@R> =>? {
        match size {
            BufferSize::Finite(n) => {
                if channel.len() as i32 > n {
                    Err(lalrpop_util::ParseError::User {
                        error: crate::parse::CustomError::BufferOverflow {
                            size: n,
                            actual: channel.len() as i32,
                            from,
                            to,
                        },
                    })
                } else {
                    Ok((size, channel))
                }
            }
            BufferSize::Infinite => {
                Ok((size, channel))
            }
        }
    }
};

LTLProperty: (SourceSpan, LTLFormula) = {
    "check" <l:@L> <ltl:LTLFormula> <r:@R> =>
        ((l, r - l).into(), ltl),
};


// LTL Formula with precedence
LTLFormula_ = LTLFormula;
LTLFormula: LTLFormula = {
    #[precedence(level="0")]
    <l:AExpr_> <op:RelOp> <r:AExpr_> => LTLFormula::Rel(l, op, r),
    "true" => LTLFormula::Bool(true),
    "false" => LTLFormula::Bool(false),
    "init" => LTLFormula::Locator(Locator::Init),
    "stuck" => LTLFormula::Locator(Locator::Stuck),
    "terminated" => LTLFormula::Locator(Locator::Terminated),
    "!" <LTLFormula> => LTLFormula::Not(Box::new(<>)),
    "X" <LTLFormula> => LTLFormula::Next(Box::new(<>)),
    "G" <LTLFormula> => LTLFormula::Globally(Box::new(<>)),
    "F" <LTLFormula> => LTLFormula::Finally(Box::new(<>)),
    "(" <LTLFormula_> ")",
    <OperationP> => LTLFormula::Operation(<>),
    <ChannelName> "?" <AExpr> => LTLFormula::ChannelFormula(ChannelFormula::ChannelHead(<>)),
    <ChannelName> "??" <AExpr> => LTLFormula::ChannelFormula(ChannelFormula::ChannelContains(<>)),

    #[precedence(level="1")] #[assoc(side="left")]
    <l:LTLFormula> "&" <r:LTLFormula> => LTLFormula::And(Box::new(l), Box::new(r)),

    #[precedence(level="2")] #[assoc(side="left")]
    <l:LTLFormula> "|" <r:LTLFormula> => LTLFormula::Or(Box::new(l), Box::new(r)),

    #[precedence(level="3")] #[assoc(side="right")]
    <l:LTLFormula> "==>" <r:LTLFormula> => LTLFormula::Implies(Box::new(l), Box::new(r)),

    #[precedence(level="6")] #[assoc(side="right")]
    <l:LTLFormula> "U" <r:LTLFormula> => LTLFormula::Until(Box::new(l), Box::new(r)),
};
